In [5]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

file_name = next(iter(uploaded))
df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("File name:", file_name)
print("Number of rows:", len(df))

display(df.head())

Saving archive (1).zip to archive (1).zip
Dataset loaded successfully!
File name: archive (1).zip
Number of rows: 250000

,manufacturer,model,type,drive_type,fuel_type,color,battery_kwh,range_km,charging_time_hr,fast_charging,...,city,seats,price_usd,efficiency_score,acceleration_0_100_kmph,top_speed_kmph,warranty_years,cargo_space_liters,safety_rating,target_high_efficiency
0,BYD,Model S,Coupe,FWD,Electric,Blue,84.93,464.06,0.85,True,...,Shanghai,7,32213.0,5.394897,5.84,136.00,3,248.9,3.3,1
1,Lucid,EV6,Sedan,AWD,Electric,Blue,65.14,345.36,2.03,True,...,Tokyo,7,31125.0,5.067074,3.86,149.34,5,504.3,3.6,1
2,Volkswagen,EV6,SUV,FWD,Hybrid,White,22.75,104.25,0.22,True,...,Oslo,5,15674.0,5.057602,2.85,275.80,5,424.9,4.2,1
3,BMW,Ioniq,Sedan,AWD,Hybrid,Black,71.72,341.74,0.48,False,...,Vancouver,2,24044.0,4.826029,3.78,130.41,8,398.5,4.9,0
4,Volkswagen,Model 3,Truck,AWD,Hybrid,Green,62.99,338.16,0.79,True,...,Shenzhen,4,29567.0,5.222624,7.07,253.31,7,411.4,3.4,1

In [10]:
import pandas as pd

print("ACTIVITY 1")
print("Statistical Analysis Using Built-in Functions")

print("\nNumerical columns:")
print(df.select_dtypes(include='number').columns.tolist())


print("1. Frequency ")
print("Attribute: release_year")

frequency = df['release_year'].value_counts().sort_index()
print(frequency)


print("2. Mean ")
print("Attribute: range_km")

mean_range = df['range_km'].mean()
print("Mean Range =", round(mean_range, 2), "km")


print("3. Median ")
print("Attribute: price_usd")

median_price = df['price_usd'].median()
print("Median Price =", round(median_price, 2), "USD")


print(" 4. Mode ")
print("Attribute: battery_kwh")

mode_battery = df['battery_kwh'].mode()
print("Mode Battery Capacity =", mode_battery.tolist(), "kWh")


print("5. Range ")
print("Attribute: top_speed_kmph")

maximum_speed = df['top_speed_kmph'].max()
minimum_speed = df['top_speed_kmph'].min()

speed_range = maximum_speed - minimum_speed

print("Maximum =", maximum_speed)
print("Minimum =", minimum_speed)
print("Range =", round(speed_range, 2), "km/h")


print(" 6. Variance ")
print("Attribute: acceleration_0_100_kmph")

variance_acceleration = df['acceleration_0_100_kmph'].var()
print("Variance =", round(variance_acceleration, 4))


print(" 7. Standard Deviation ")
print("Attribute: efficiency_score")

standard_deviation = df['efficiency_score'].std()
print("Standard Deviation =", round(standard_deviation, 4))


print(" 8. Interquartile Range ")
print("Attribute: cargo_space_liters")

Q1 = df['cargo_space_liters'].quantile(0.25)
Q3 = df['cargo_space_liters'].quantile(0.75)

IQR = Q3 - Q1

print("Q1 =", round(Q1, 2))
print("Q3 =", round(Q3, 2))
print("IQR =", round(IQR, 2))


print("ACTIVITY 1 SUMMARY")

print("Frequency          : release_year")
print("Mean               : range_km")
print("Median             : price_usd")
print("Mode               : battery_kwh")
print("Range              : top_speed_kmph")
print("Variance           : acceleration_0_100_kmph")
print("Standard Deviation : efficiency_score")
print("IQR                : cargo_space_liters")

ACTIVITY 1
Statistical Analysis Using Built-in Functions

Numerical columns:
['battery_kwh', 'range_km', 'charging_time_hr', 'release_year', 'seats', 'price_usd', 'efficiency_score', 'acceleration_0_100_kmph', 'top_speed_kmph', 'warranty_years', 'cargo_space_liters', 'safety_rating', 'target_high_efficiency']
1. Frequency
Attribute: release_year
release_year
2012    17915
2013    17557
2014    17896
2015    17795
2016    17929
2017    17785
2018    17932
2019    17788
2020    17755
2021    18003
2022    17832
2023    17809
2024    17958
2025    18046
Name: count, dtype: int64
2. Mean
Attribute: range_km
Mean Range = 375.12 km
3. Median
Attribute: price_usd
Median Price = 30502.0 USD
 4. Mode
Attribute: battery_kwh
Mode Battery Capacity = [76.09] kWh
5. Range
Attribute: top_speed_kmph
Maximum = 280.0
Minimum = 120.0
Range = 160.0 km/h
 6. Variance
Attribute: acceleration_0_100_kmph
Variance = 4.6941
 7. Standard Deviation
Attribute: efficiency_score
Standard Deviation = 0.7643
 8. Interquartile Range
Attribute: cargo_space_liters
Q1 = 382.5
Q3 = 517.3
IQR = 134.8
ACTIVITY 1 SUMMARY
Frequency          : release_year
Mean               : range_km
Median             : price_usd
Mode               : battery_kwh
Range              : top_speed_kmph
Variance           : acceleration_0_100_kmph
Standard Deviation : efficiency_score
IQR                : cargo_space_liters

In [13]:
import math



def calculate_mean(data):
    total = 0
    count = 0

    for value in data:
        total = total + value
        count = count + 1

    return total / count




def calculate_median(data):
    sorted_data = sorted(data)
    n = len(sorted_data)

    if n % 2 == 0:
        middle1 = sorted_data[(n // 2) - 1]
        middle2 = sorted_data[n // 2]
        median = (middle1 + middle2) / 2
    else:
        median = sorted_data[n // 2]

    return median




def calculate_mode(data):
    frequency = {}

    for value in data:
        if value in frequency:
            frequency[value] = frequency[value] + 1
        else:
            frequency[value] = 1

    highest_frequency = 0

    for value in frequency:
        if frequency[value] > highest_frequency:
            highest_frequency = frequency[value]

    modes = []

    for value in frequency:
        if frequency[value] == highest_frequency:
            modes.append(value)

    return modes




def calculate_variance(data):
    mean = calculate_mean(data)

    total = 0

    for value in data:
        difference = value - mean
        squared_difference = difference ** 2
        total = total + squared_difference

    variance = total / len(data)

    return variance




def calculate_standard_deviation(data):
    variance = calculate_variance(data)
    return math.sqrt(variance)




def calculate_iqr(data):
    sorted_data = sorted(data)

    n = len(sorted_data)

    if n % 2 == 0:
        lower_half = sorted_data[:n // 2]
        upper_half = sorted_data[n // 2:]
    else:
        lower_half = sorted_data[:n // 2]
        upper_half = sorted_data[(n // 2) + 1:]

    Q1 = calculate_median(lower_half)
    Q3 = calculate_median(upper_half)

    IQR = Q3 - Q1

    return Q1, Q3, IQR




range_data = []
price_data = []
battery_data = []
acceleration_data = []
efficiency_data = []
cargo_data = []


for value in df['range_km']:
    if not pd.isna(value):
        range_data.append(value)


for value in df['price_usd']:
    if not pd.isna(value):
        price_data.append(value)


for value in df['battery_kwh']:
    if not pd.isna(value):
        battery_data.append(value)


for value in df['acceleration_0_100_kmph']:
    if not pd.isna(value):
        acceleration_data.append(value)


for value in df['efficiency_score']:
    if not pd.isna(value):
        efficiency_data.append(value)


for value in df['cargo_space_liters']:
    if not pd.isna(value):
        cargo_data.append(value)




mean_range = calculate_mean(range_data)

print("1. Mean ")
print("Attribute: range_km")
print("Mean Range =", round(mean_range, 2), "km")



median_price = calculate_median(price_data)

print(" 2. Median ")
print("Attribute: price_usd")
print("Median Price =", round(median_price, 2), "USD")



mode_battery = calculate_mode(battery_data)

print(" 3. Mode ")
print("Attribute: battery_kwh")
print("Mode Battery Capacity =", mode_battery, "kWh")


variance_acceleration = calculate_variance(acceleration_data)

print("4. Variance ")
print("Attribute: acceleration_0_100_kmph")
print("Variance =", round(variance_acceleration, 4))



standard_deviation = calculate_standard_deviation(efficiency_data)

print("5. Standard Deviation ")
print("Attribute: efficiency_score")
print("Standard Deviation =", round(standard_deviation, 4))



Q1, Q3, IQR = calculate_iqr(cargo_data)

print("6. Interquartile Range ")
print("Attribute: cargo_space_liters")
print("Q1 =", round(Q1, 2))
print("Q3 =", round(Q3, 2))
print("IQR =", round(IQR, 2))





print("ACTIVITY 2 FINAL RESULTS")


print("Mean               =", round(mean_range, 2))
print("Median             =", round(median_price, 2))
print("Mode               =", mode_battery)
print("Variance            =", round(variance_acceleration, 4))
print("Standard Deviation  =", round(standard_deviation, 4))
print("Q1                  =", round(Q1, 2))
print("Q3                  =", round(Q3, 2))
print("IQR                 =", round(IQR, 2))

1. Mean
Attribute: range_km
Mean Range = 375.12 km
 2. Median
Attribute: price_usd
Median Price = 30502.0 USD
 3. Mode
Attribute: battery_kwh
Mode Battery Capacity = [76.09] kWh
4. Variance
Attribute: acceleration_0_100_kmph
Variance = 4.6941
5. Standard Deviation
Attribute: efficiency_score
Standard Deviation = 0.7643
6. Interquartile Range
Attribute: cargo_space_liters
Q1 = 382.5
Q3 = 517.3
IQR = 134.8
ACTIVITY 2 FINAL RESULTS
Mean               = 375.12
Median             = 30502.0
Mode               = [76.09]
Variance            = 4.6941
Standard Deviation  = 0.7643
Q1                  = 382.5
Q3                  = 517.3
IQR                 = 134.8

In [14]:


import pandas as pd
import math


data = df['range_km'].dropna()

print("ACTIVITY 3")
print("Grouped Data Analysis")
print("Attribute Used: range_km")
print("Number of observations:", len(data))



bins = [0, 100, 200, 300, 400, 500, 600, 700, 800]

labels = [
    '0-100',
    '101-200',
    '201-300',
    '301-400',
    '401-500',
    '501-600',
    '601-700',
    '701-800'
]


groups = pd.cut(
    data,
    bins=bins,
    labels=labels,
    include_lowest=True
)


frequency = groups.value_counts().sort_index()


midpoints = [
    50,
    150.5,
    250.5,
    350.5,
    450.5,
    550.5,
    650.5,
    750.5
]


grouped_data = pd.DataFrame({
    'Class Interval': labels,
    'Frequency': frequency.values,
    'Midpoint': midpoints
})


N = grouped_data['Frequency'].sum()


grouped_data['f × x'] = (
    grouped_data['Frequency'] *
    grouped_data['Midpoint']
)


grouped_data['Cumulative Frequency'] = (
    grouped_data['Frequency'].cumsum()
)

print("GROUPED DATA TABLE ")
display(grouped_data)

print("Total Frequency =", N)



sum_fx = grouped_data['f × x'].sum()

grouped_mean = sum_fx / N

print("\n========== GROUPED MEAN ==========")
print("Σ(f × x) =", sum_fx)
print("Σf =", N)
print("Grouped Mean =", round(grouped_mean, 2), "km")



median_position = N / 2

median_class_index = (
    grouped_data['Cumulative Frequency']
    >= median_position
).idxmax()

median_class = grouped_data.iloc[median_class_index]

L = bins[median_class_index]
f = median_class['Frequency']

if median_class_index == 0:
    CF = 0
else:
    CF = grouped_data.iloc[
        median_class_index - 1
    ]['Cumulative Frequency']

h = 100

grouped_median = L + (
    (median_position - CF) / f
) * h

print("GROUPED MEDIAN ")
print("N/2 =", median_position)
print("Median Class =", median_class['Class Interval'])
print("Grouped Median =", round(grouped_median, 2), "km")



modal_class_index = grouped_data['Frequency'].idxmax()

modal_class = grouped_data.iloc[modal_class_index]

fm = modal_class['Frequency']

if modal_class_index == 0:
    f1 = 0
else:
    f1 = grouped_data.iloc[
        modal_class_index - 1
    ]['Frequency']

if modal_class_index == len(grouped_data) - 1:
    f2 = 0
else:
    f2 = grouped_data.iloc[
        modal_class_index + 1
    ]['Frequency']

L = bins[modal_class_index]

grouped_mode = L + (
    (fm - f1) /
    ((fm - f1) + (fm - f2))
) * h

print(" GROUPED MODE")
print("Modal Class =", modal_class['Class Interval'])
print("Grouped Mode =", round(grouped_mode, 2), "km")



grouped_data['f × x²'] = (
    grouped_data['Frequency'] *
    grouped_data['Midpoint'] ** 2
)

sum_fx2 = grouped_data['f × x²'].sum()

grouped_variance = (
    sum_fx2 / N
) - (grouped_mean ** 2)

print(" GROUPED VARIANCE")
print("Σ(f × x²) =", sum_fx2)
print("Grouped Variance =", round(grouped_variance, 2))



grouped_std = math.sqrt(grouped_variance)

print("\n========== GROUPED STANDARD DEVIATION ==========")
print(
    "Grouped Standard Deviation =",
    round(grouped_std, 2),
    "km"
)



Q1_position = N / 4

Q1_class_index = (
    grouped_data['Cumulative Frequency']
    >= Q1_position
).idxmax()

Q1_class = grouped_data.iloc[Q1_class_index]

L1 = bins[Q1_class_index]
f_Q1 = Q1_class['Frequency']

if Q1_class_index == 0:
    CF_Q1 = 0
else:
    CF_Q1 = grouped_data.iloc[
        Q1_class_index - 1
    ]['Cumulative Frequency']

Q1 = L1 + (
    (Q1_position - CF_Q1) / f_Q1
) * h



Q3_position = 3 * N / 4

Q3_class_index = (
    grouped_data['Cumulative Frequency']
    >= Q3_position
).idxmax()

Q3_class = grouped_data.iloc[Q3_class_index]

L3 = bins[Q3_class_index]
f_Q3 = Q3_class['Frequency']

if Q3_class_index == 0:
    CF_Q3 = 0
else:
    CF_Q3 = grouped_data.iloc[
        Q3_class_index - 1
    ]['Cumulative Frequency']

Q3 = L3 + (
    (Q3_position - CF_Q3) / f_Q3
) * h



grouped_IQR = Q3 - Q1

print(" GROUPED IQR")
print("Q1 =", round(Q1, 2), "km")
print("Q3 =", round(Q3, 2), "km")
print("Grouped IQR =", round(grouped_IQR, 2), "km")



print("       ACTIVITY 3 FINAL RESULTS")


print("Attribute              : range_km")
print("Total Frequency         :", N)
print("Grouped Mean            :", round(grouped_mean, 2), "km")
print("Grouped Median          :", round(grouped_median, 2), "km")
print("Grouped Mode            :", round(grouped_mode, 2), "km")
print("Grouped Variance        :", round(grouped_variance, 2))
print("Grouped Std. Deviation  :", round(grouped_std, 2), "km")
print("Grouped Q1              :", round(Q1, 2), "km")
print("Grouped Q3              :", round(Q3, 2), "km")
print("Grouped IQR             :", round(grouped_IQR, 2), "km")

ACTIVITY 3
Grouped Data Analysis
Attribute Used: range_km
Number of observations: 250000
GROUPED DATA TABLE

  Class Interval  Frequency  Midpoint       f × x  Cumulative Frequency
0          0-100        816      50.0     40800.0                   816
1        101-200      10963     150.5   1649931.5                 11779
2        201-300      51350     250.5  12863175.0                 63129
3        301-400      88309     350.5  30952304.5                151438
4        401-500      66019     450.5  29741559.5                217457
5        501-600      25827     550.5  14217763.5                243284
6        601-700       5860     650.5   3811930.0                249144
7        701-800        765     750.5    574132.5                249909

Total Frequency = 249909

========== GROUPED MEAN ==========
Σ(f × x) = 93851596.5
Σf = 249909
Grouped Mean = 375.54 km
GROUPED MEDIAN
N/2 = 124954.5
Median Class = 301-400
Grouped Median = 370.01 km
 GROUPED MODE
Modal Class = 301-400
Grouped Mode = 362.38 km
 GROUPED VARIANCE
Σ(f × x²) = 38457361023.25
Grouped Variance = 12852.85

========== GROUPED STANDARD DEVIATION ==========
Grouped Standard Deviation = 113.37 km
 GROUPED IQR
Q1 = 298.73 km
Q3 = 454.52 km
Grouped IQR = 155.79 km
       ACTIVITY 3 FINAL RESULTS
Attribute              : range_km
Total Frequency         : 249909
Grouped Mean            : 375.54 km
Grouped Median          : 370.01 km
Grouped Mode            : 362.38 km
Grouped Variance        : 12852.85
Grouped Std. Deviation  : 113.37 km
Grouped Q1              : 298.73 km
Grouped Q3              : 454.52 km
Grouped IQR             : 155.79 km